version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: oj-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: note
      MYSQL_USER: ojuser
      MYSQL_PASSWORD: ojpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./boot/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./boot
    container_name: oj-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/note?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ojuser
      SPRING_DATASOURCE_PASSWORD: ojpassword

  frontend:
    build:
      context: ./Vue
      dockerfile: Dockerfile
    container_name: oj-frontend
    ports:
      - "8080:80"
    volumes:
      - ./Vue/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
    environment:
      TZ: Asia/Shanghai

volumes:
  db-data:
